### ISSUE TITLE
netd pods stuck in Init:0/1 after upgrading GKE from 1.31.x to 1.32.x

### ISSUE THREAD

**Issue by dotdc** [GoogleCloudPlatform/netd#440]
Hello,

After upgrading some GKE clusters from version `v1.31.7-gke.1212000` to `v1.32.3-gke.1785003`, we noticed that all netd pods are stuck in the `Init:0/1` state across all nodes/nodepools running GKE 1.32.x, this is not the case on the ones still running on GKE 1.31.x.

Netd images on `v1.31.7-gke.1212000` (working) ✅ :
```
gke.gcr.io/netd-init:v0.9.3-gke.6@sha256:9a3a71449bf45a9f3ce62d81f18ae3f610dd4f61add240953107426bb9df2ee8
gke.gcr.io/netd:v0.9.3-gke.6@sha256:42eabe7305d0e842f39bc3ab19de150d36c2464e218368e775308c306c11478c
```

Netd images on `v1.32.3-gke.1785003` (failing) ❌ :
```
gke.gcr.io/netd-init:v0.9.7-gke.1@sha256:b3361a41f21d1b09895b3209a828fbd1cbe7c2dcac96a391d6d202eb3a37803d
gke.gcr.io/netd:v0.9.7-gke.1@sha256:d09bb89144daeb649ffde70d15c789e9c90b24f7501236f6f39c0c4ca4b3c3d0
```

> [!IMPORTANT]
> Affected clusters are still using GKE Dataplane V1

Pods status:
```
$ kubectl get po -n kube-system -l k8s-app=netd
NAME         READY   STATUS     RESTARTS   AGE
netd-48kx5   0/2     Init:0/1   0          12h
netd-q9n57   0/2     Init:0/1   0          12h
...
netd-qbdcd   0/2     Init:0/1   0          12h
netd-qkgjz   0/2     Init:0/1   0          12h
```

Netd init container logs:
```
$ kubectl logs -n kube-system netd-48kx5 -c install-cni
Install-CNI (/netd-init), Build: v0.9.7-gke.1-linux-amd64
Calico network policy enabled: 'true'; write config: 'false'
inotify: calling /netd-init as initial run
Listing items matching /host/etc/cni/net.d/*calico*.conflist
(this action repeats during bootstrap until a match is found)
inotify: /netd-init exited with status 256 (exit: 1)
inotify: calling /netd-init after 2001ms since the last run
Listing items matching /host/etc/cni/net.d/*calico*.conflist
(this action repeats during bootstrap until a match is found)
inotify: /netd-init exited with status 256 (exit: 1)
...
inotify: calling /netd-init for 2 matching event(s)
Listing items matching /host/etc/cni/net.d/*calico*.conflist
(this action repeats during bootstrap until a match is found)
/host/etc/cni/net.d/10-calico.conflist
inotify: /netd-init exited with status 0 (exit: 0)
Calico has written CNI config files. No action needed here.
Install-CNI execution completed successfully.
Running CNI watchdog; sleeping infinity now.
```

Is this a known issue with netd on GKE 1.32.x?
Could it be linked to a third-party component?
Any ideas?

Thank you in advance.

**Comment by jingyuanliang** [comment]
Could you inspect your pod and check if .spec.initContainers[0].restartPolicy is missing? (supposed to be "Always")

We've seen some support case which ends up with user's mutating webhook modifying system objects unexpectedly.

**Comment by dotdc** [comment]
@jingyuanliang The restartPolicy is here and set to `Always` 👍 

Here's the pod manifest:
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    components.gke.io/component-name: netd-combined
    components.gke.io/component-version: 12.2.12
  labels:
    k8s-app: netd
  name: netd-48kx5
  namespace: kube-system
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - my-node
  containers:
  - args:
    - --enable-policy-routing=$(ENABLE_POLICY_ROUTING)
    - --enable-source-valid-mark=$(ENABLE_SOURCE_VALID_MARK)
    - --exclude-dns=$(EXCLUDE_DNS)
    - --logtostderr
    - --reconcile-interval-seconds=$(RECONCILE_INTERVAL_SECONDS)
    - --metrics-collectors=$(METRICS_COLLECTORS)
    - --metrics-address=$(METRICS_ADDRESS)
    - --stack-type=$(STACK_TYPE)
    env:
    - name: ENABLE_POLICY_ROUTING
      value: "true"
    - name: ENABLE_SOURCE_VALID_MARK
      value: "true"
    - name: EXCLUDE_DNS
      value: "false"
    - name: RECONCILE_INTERVAL_SECONDS
      valueFrom:
        configMapKeyRef:
          key: reconcile_interval_seconds
          name: netd-config
    - name: METRICS_COLLECTORS
      valueFrom:
        configMapKeyRef:
          key: metrics_collectors
          name: networking-metrics-config
    - name: METRICS_ADDRESS
      valueFrom:
        configMapKeyRef:
          key: metrics_address
          name: networking-metrics-config
    - name: STACK_TYPE
      valueFrom:
        configMapKeyRef:
          key: stack_type
          name: networking-metrics-config
    - name: CURRENT_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: gke.gcr.io/netd:v0.9.7-gke.1@sha256:d09bb89144daeb649ffde70d15c789e9c90b24f7501236f6f39c0c4ca4b3c3d0
    imagePullPolicy: IfNotPresent
    name: netd
    resources:
      requests:
        cpu: 2m
        memory: 30Mi
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/var/lib/cni/networks/gke-pod-network
      name: gke-pod-network
      readOnly: true
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-znw5m
      readOnly: true
  - env:
    - name: GOMAXPROCS
      value: "2"
    - name: COLLECTOR_CONFIG_PATH
      value: /conf/netd-metrics-collector-config-data.textproto
    - name: SPLIT_GAUGE_BUFFER
      value: "true"
    - name: PROJECT_NUMBER
      value: "XXXXXXXXXXXXX"
    - name: LOCATION
      value: europe-west1
    - name: CLUSTER_NAME
      value: myclusternamehere
    - name: METRICS_ADDRESS
      valueFrom:
        configMapKeyRef:
          key: metrics_address
          name: networking-metrics-config
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: CONTAINER_NAME
      value: netd-metrics-collector
    - name: COMPONENT_VERSION
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['components.gke.io/component-version']
    - name: COMPONENT_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations['components.gke.io/component-name']
    image: gke.gcr.io/gke-metrics-collector:20250219_2300_RC0@sha256:417803914b2912d9d64e2df7b9cfc8770675076ed912b3ec1f52a0e4104f6f5f
    imagePullPolicy: IfNotPresent
    name: netd-metrics-collector
    resources:
      limits:
        cpu: "1"
        memory: 65Mi
      requests:
        cpu: 5m
        memory: 30Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /conf
      name: netd-metrics-collector-config-map-vol
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-znw5m
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - env:
    - name: MIGRATE_TO_DPV2
      value: "false"
    - name: CNI_SPEC_TEMPLATE
      valueFrom:
        configMapKeyRef:
          key: cni_spec_template
          name: netd-config
    - name: CNI_SPEC_NAME
      valueFrom:
        configMapKeyRef:
          key: cni_spec_name
          name: netd-config
    - name: CNI_SPEC_IPV6_ROUTE
      valueFrom:
        configMapKeyRef:
          key: cni_spec_ipv6_route
          name: netd-config
    - name: ENABLE_CALICO_NETWORK_POLICY
      valueFrom:
        configMapKeyRef:
          key: enable_calico_network_policy
          name: netd-config
    - name: WRITE_CALICO_CONFIG_FILE
      value: "false"
    - name: ENABLE_IPV6
      valueFrom:
        configMapKeyRef:
          key: enable_ipv6
          name: netd-config
    - name: ENABLE_CILIUM_PLUGIN
      valueFrom:
        configMapKeyRef:
          key: enable_cilium_plugin
          name: netd-config
    - name: ISTIO_CNI_CONFIG
      valueFrom:
        configMapKeyRef:
          key: cni_network_config
          name: istio-cni-plugin-config
          optional: true
    - name: KUBERNETES_SERVICE_HOST
      valueFrom:
        configMapKeyRef:
          key: master_ip
          name: netd-config
    - name: CILIUM_CHAINING_MODE
      valueFrom:
        configMapKeyRef:
          key: cilium_chaining_mode
          name: netd-config
    - name: CURRENT_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: CILIUM_FAST_START_NAMESPACES
      valueFrom:
        configMapKeyRef:
          key: fast-start-namespaces
          name: dpv2-fast-start-config
          optional: true
    - name: RUN_CNI_WATCHDOG
      value: "true"
    - name: CILIUM_WATCHDOG_SUCCESS_WAIT
      valueFrom:
        configMapKeyRef:
          key: cilium_watchdog_success_wait_seconds
          name: netd-config
    - name: CILIUM_WATCHDOG_FAILURE_RETRY
      valueFrom:
        configMapKeyRef:
          key: cilium_watchdog_failure_retry_seconds
          name: netd-config
    - name: CILIUM_WATCHDOG_FAST_START_WAIT
      valueFrom:
        configMapKeyRef:
          key: cilium_watchdog_fast_start_wait_seconds
          name: netd-config
    image: gke.gcr.io/netd-init:v0.9.7-gke.1@sha256:b3361a41f21d1b09895b3209a828fbd1cbe7c2dcac96a391d6d202eb3a37803d
    imagePullPolicy: IfNotPresent
    name: install-cni
    resources:
      requests:
        cpu: 1m
        memory: 5Mi
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /host/etc/cni/net.d
      name: cni-net-dir
    - mountPath: /host/home/kubernetes/bin
      name: kubernetes-bin
      readOnly: true
    - mountPath: /run/xtables.lock
      name: xtables-lock
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-znw5m
      readOnly: true
  nodeName: my-node
  nodeSelector:
    cloud.google.com/gke-netd-ready: "true"
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: netd
  serviceAccountName: netd
  terminationGracePeriodSeconds: 0
  tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  - key: components.gke.io/gke-managed-components
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/cni/net.d
      type: Directory
    name: cni-net-dir
  - hostPath:
      path: /home/kubernetes/bin
      type: Directory
    name: kubernetes-bin
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: xtables-lock
  - hostPath:
      path: /var/lib/cni/networks/gke-pod-network
      type: DirectoryOrCreate
    name: gke-pod-network
  - configMap:
      defaultMode: 420
      items:
      - key: netd-metrics-collector-config-data
        path: netd-metrics-collector-config-data.textproto
      name: netd-metrics-collector-config-map
    name: netd-metrics-collector-config-map-vol
  - name: kube-api-access-znw5m
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

**Comment by jingyuanliang** [comment]
No it's not set correctly in your case. I was talking about a restartPolicy under initContainers, not at the pod level.

In that customer case, it was broken by a customer-deployed https://github.com/doitintl/gtoken/ installation, while yours might be on others.

**Comment by dotdc** [comment]
@jingyuanliang It's missing from the pod manifest but it was present on the Daemonset manifest, sorry for the confusion...
The `restartPolicy` field gets ignored when the Daemonset pods are created because you apparently can't set a `restartPolicy` for individual containers on a Daemonset. 

Since the init-container only run once, even with the pod's `restartPolicy`, I've tried to convert it back to a regular container and it worked!

```
$ kubectl get po -n kube-system -l k8s-app=netd
netd-b9cbs                                                       3/3     Running   0             3s
netd-dp6kt                                                       3/3     Running   0             3s
...
netd-zlf8p                                                       3/3     Running   0             3s
netd-zq7wg                                                       3/3     Running   0             3s
```

As this is a GKE managed component, I'm wondering how to fix this issue in the longterm.

Wdyt?

**Comment by dotdc** [comment]
Found the old/badly configured `mutatingwebhookconfiguration` and excluded  `kube-system` pods by adding:

```
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
```

Works just fine! 👌 

@jingyuanliang Thank you for your help!
